!group
id: "icon-sets_group"
name: Icon sets
desc: "All icons on Iconfinder are organized into sets created by a specific author. Sets share a set of common attributes, such as licensing, pricing etc."
